name: Build Debian Package

on:
  push:
    branches: [ master ]
    tags: [  v*]

jobs:
  build-debian-package:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: write

    steps:
    - name: Set up container environment
      run: |
        apt-get update
        apt-get install -y \
          ca-certificates \
          git wget

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: download and make pkg
      run: |
        ./build.sh
        dpkg-deb --build server-tools server-tools.deb

    - name: List built packages
      run: |
        ls -l *.deb

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.deb" # Specify path to artifacts to be attached
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token
