
name: Build Debian Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-debian-package:
    container: 
      image: debian:bullseye
    
    runs-on: debian-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Update package lists and install dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          debhelper \
          devscripts \
          git \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-all \
          dh-python \
          gpg \
          wget \
          ca-certificates
    
    - name: Prepare package metadata
    
    - name: Build Debian Package
      run: |
        ./build.sh && cd server-tools && dpkg-buildpackage -us -uc -b
    
    - name: List built packages
      run: |
        find . -name '*.deb' -ls
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-packages
        path: server-tools/*.deb
        retention-days: 5
